#!/usr/bin/env python
# encoding: utf-8
# Migration script to convert old leetcode_to_neetcode.py format to new format with shorts support
# This script will create a backup and update the data structure to support both videos and shorts

import json
import os
import shutil
from typing import Dict, Any


def migrate_old_to_new_format(old_data: Dict[str, Any]) -> Dict[str, Any]:
    """
    Convert old data format to new format that supports both videos and shorts.

    Args:
        old_data: Dictionary in old format {problem_id: {title, url}}

    Returns:
        Dictionary in new format {problem_id: {video: {title, url}, short: {title, url}}}
    """
    new_data = {}

    for problem_id, video_info in old_data.items():
        new_data[problem_id] = {"video": video_info}

    return new_data


def main():
    """Main migration function."""
    # File paths
    current_file = "leetcode_study_tool/leetcode_to_neetcode.py"
    backup_file = "leetcode_study_tool/leetcode_to_neetcode.py.backup"
    youtube_json = "youtube.json"

    print("Starting migration of leetcode_to_neetcode.py to support shorts...")

    # Step 1: Create backup
    if os.path.exists(current_file):
        shutil.copy2(current_file, backup_file)
        print(f"✓ Created backup: {backup_file}")

    # Step 2: Read current data from Python file
    try:
        # Read the current Python file content
        with open(current_file, "r", encoding="utf-8") as f:
            content = f.read()

        # Extract the dictionary using exec (safe in this controlled context)
        namespace = {}
        exec(content, namespace)
        old_data = namespace.get("LEETCODE_TO_NEETCODE", {})

        print(f"✓ Read current data: {len(old_data)} entries")

    except Exception as e:
        print(f"✗ Error reading current data: {e}")
        return

    # Step 3: Migrate to new format
    new_data = migrate_old_to_new_format(old_data)

    # Step 4: Write new format back to Python file
    try:
        # Generate new Python file content
        new_content = "# Auto-generated mapping of LeetCode problems to NeetCode videos and shorts\n"
        new_content += "# This file supports both regular videos and shorts\n"
        new_content += "# Generated by migration script\n\n"
        new_content += "LEETCODE_TO_NEETCODE = {\n"

        for problem_id in sorted(new_data.keys(), key=int):
            content = new_data[problem_id]
            new_content += f'    "{problem_id}": {{\n'

            if "video" in content:
                video = content["video"]
                new_content += f'        "video": {{\n'
                new_content += f'            "title": {json.dumps(video["title"], ensure_ascii=False)},\n'
                new_content += f'            "url": {json.dumps(video["url"], ensure_ascii=False)},\n'
                new_content += "        },\n"

            if "short" in content:
                short = content["short"]
                new_content += f'        "short": {{\n'
                new_content += f'            "title": {json.dumps(short["title"], ensure_ascii=False)},\n'
                new_content += f'            "url": {json.dumps(short["url"], ensure_ascii=False)},\n'
                new_content += "        },\n"

            new_content += "    },\n"

        new_content += "}\n"

        with open(current_file, "w", encoding="utf-8") as f:
            f.write(new_content)

        print(f"✓ Updated {current_file} to new format")

    except Exception as e:
        print(f"✗ Error writing new format: {e}")
        return

    # Step 5: Check if youtube.json needs migration too
    if os.path.exists(youtube_json):
        try:
            with open(youtube_json, "r", encoding="utf-8") as f:
                youtube_data = json.load(f)

            # Check if it's old format (has direct title/url properties)
            if any(
                "title" in v and "url" in v
                for v in youtube_data.values()
                if isinstance(v, dict)
            ):
                print(f"✓ Detected old format in {youtube_json}")

                # Migrate youtube.json as well
                migrated_youtube_data = migrate_old_to_new_format(youtube_data)

                with open(youtube_json, "w", encoding="utf-8") as f:
                    json.dump(
                        migrated_youtube_data,
                        f,
                        indent=4,
                        sort_keys=True,
                        ensure_ascii=False,
                    )

                print(f"✓ Migrated {youtube_json} to new format")
            else:
                print(f"✓ {youtube_json} already in new format")

        except Exception as e:
            print(f"✗ Error migrating {youtube_json}: {e}")

    print("\nMigration completed successfully!")
    print(f"📁 Original data backed up to: {backup_file}")
    print(f"📄 Updated file: {current_file}")
    print("\nNext steps:")
    print("1. Update the formatters to handle the new data structure")
    print("2. Update the HTML template to display shorts")
    print("3. Test with sample data")


if __name__ == "__main__":
    main()
